In [1]:
import pandas as pd
alunos = {'Nomes':['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
         'Nota':[4,7,5.5,9],
         'Aprovado':['Não','Sim','Não','Sim']}

In [2]:
dataframe = pd.DataFrame(alunos)

In [3]:
print(dataframe)

     Nomes  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim


In [7]:
objeto1 = pd.Series([2,6,9,10,5]) #cria um vetor unidimensional e indexado a partir de uma lista
print(objeto1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [5]:
import numpy as np
array1 = np.array([6,12,2,9,10])
array2 = np.array([(2,6,9,10,5),(6,12,2,9,10)])
print(array1)
print(array2)

[ 6 12  2  9 10]
[[ 2  6  9 10  5]
 [ 6 12  2  9 10]]


In [6]:
objeto2 = pd.Series(array1)
print(objeto2)

0     6
1    12
2     2
3     9
4    10
dtype: int64
