In [4]:
import numpy as np #unica diferença é que ao inves de chamar por numpy usa np, um tipo de codinome
a = np.array([1,2,3]) #todos os elementos tem q ser do msm tipo

In [5]:
print(a)

[1 2 3]


In [12]:
b = np.array([(2, 5, 7), (5, 3, 9), (4, 6, 5)])

In [13]:
print(b)

[[2 5 7]
 [5 3 9]
 [4 6 5]]


In [9]:
c = np.zeros((4, 3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
d = np.ones((4,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
e = np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
b.max() #retorna o máximo valor na matriz

9

In [19]:
b.min() #retorna o menor valor na matriz

2

In [20]:
b.sum() #somda dos elementos da matriz

46

In [21]:
b.mean() #média dos elementos da matriz

5.111111111111111

In [23]:
b.std() #desvio padrão

1.9688939051854832